name: Build with Theos

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build (rootful)
        env:
          ARCHS: "arm64"
        run: |
          make clean package
          mkdir -p build/rootful
          mv ./packages/*.deb build/rootful/ || true

      - name: Build (rootless)
        env:
          THEOS_PACKAGE_SCHEME: rootless
          ARCHS: "arm64"
        run: |
          make clean package
          mkdir -p build/rootless
          mv ./packages/*.deb build/rootless/ || true

      - name: Upload Artifacts (rootful)
        uses: actions/upload-artifact@v4
        with:
          name: rootful-build
          path: build/rootful/*.deb

      - name: Upload Artifacts (rootless)
        uses: actions/upload-artifact@v4
        with:
          name: rootless-build
          path: build/rootless/*.deb
