name: Build Rose
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Theos
        uses: theos/theos-action@v1
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: Rose-Tweak
          path: packages/*.deb
